custom:
  login:
    default-password: Zwsoft.2023
  csv:
    # 账号和用户
    account-user: csv/02 用户.csv
    # 用户组成员
    group-member: csv/02 用户组成员.csv


spring:
  datasource:
    # batch的使用的数据源
    spring-batch:
      username: root
      password: ysqJYKL2010
      url: jdbc:mysql://127.0.0.1:3306/spring_batch?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 源数据源
    origin-data:
      username: root
      password: ysqJYKL2010
      url: jdbc:mysql://127.0.0.1:3306/default_default?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 目标数据源
    target-data:
      username: root
      password: ysqJYKL2010
      url: jdbc:mysql://127.0.0.1:3306/default_default?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  # 当有多个DataSource时，如果不指定主数据源，sql.nit不会执行:
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: alwaysy
      mode: never
#  batch:
#    job:
#      enabled: false   #false表示不启动
mybatis-plus:
  type-aliases-package: top.ysqorz.batch.springbatch.model
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
